### ISSUE TITLE
Errors in new library

### ISSUE THREAD

**Issue by nikkadim** [Infineon/3D-Magnetic-Sensor-2GO#1]
```
...\MagneticSensor3D\src\MagneticSensor3D.cpp: In member function 'void Tlv493d::begin()':

C:\Users\xxx\Documents\Arduino\libraries\MagneticSensor3D\src\MagneticSensor3D.cpp:32:32: error: 'TRUE' was not declared in this scope

  begin(Wire, TLV493D_ADDRESS1, TRUE);
```

**Comment by nikkadim** [comment]
The keywords in C++ are lowercase true and false.

**Comment by mhollfelder** [comment]
Hi,

You are totally right, thank you very much for reporting this issue.
 
We will add another `#define` to resolve this issue or fix the problem by replacing TRUE/FALSE in the code. I assume that also other libraries from us are affected and I will check this.

Best regards,

Manuel

**Comment by mhollfelder** [comment]
We have fixed this issue with the new release which will come soon.
Code will be pushed to the master branch before the release.

Best regards,

Manuel
