### ISSUE TITLE
TLE493D-W2B6-a3

### ISSUE THREAD

**Issue by faccolo** [Infineon/3D-Magnetic-Sensor-2GO#10]
Hello,
I just bought this chip.

could i use it with Arduino?

best regards,
Francesco

**Comment by mhollfelder** [comment]
Hi Francesco,

what board do you have exactly or do you have a bare chip?

For the TLE493D-W2B6 we have an own repository which can be found here:
https://github.com/Infineon/TLE493D-3DMagnetic-Sensor 

As you have the A3 variant, you would need to change the I2C address in the source code or supply the correct one with the `Tle493d::begin()` function.

Best regards,

Manuel

**Comment by ederjc** [comment]
Hi @faccolo, has Manuel answered your question?
