### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by honnet** [Infineon/3D-Magnetic-Sensor-2GO#15]
The following line is called 3 consecutive times in the initialization:

	setRegBits(tlv493d::W_RES1, getRegBits(tlv493d::R_RES1));

https://github.com/Infineon/TLV493D-A1B6-3DMagnetic-Sensor/blob/master/src/Tlv493d.cpp#L89-L91

Shouldn't it be the following instead?

	setRegBits(tlv493d::W_RES1, getRegBits(tlv493d::R_RES1));
	setRegBits(tlv493d::W_RES2, getRegBits(tlv493d::R_RES2));
	setRegBits(tlv493d::W_RES3, getRegBits(tlv493d::R_RES3));

**Comment by 9Volts9er** [comment]
You are absolutely right. I've fixed this in my Pull-Request #21
