### ISSUE TITLE
TLV493D-A1B6 MS2GO incorrect macro names

### ISSUE THREAD

**Issue by sfeutrier** [Infineon/3D-Magnetic-Sensor-2GO#18]
In version 3.2 of the board : 

- LED2 macro is now wired to VDDSENS (power up for the sensor and pull-up). 
- LED1 macro is wired to the physical led LED2
- Physical LED1 does not seem to be able to turn on (not sure for that)

See infineon document : https://www.infineon.com/dgdl/Infineon-Infineon-3DMS2GO_TLv493D-A1B6-UM-v01_02-EN-UM-v01-UserManual-v01_02-EN.pdf?fileId=5546d462525dbac40152ac4ca1d318c2

**Comment by 9Volts9er** [comment]
You are right, for this board the names are not correct. 
I wanted to see, if the naming is switched also for the XMC2Go-Board, which is clearly the base of design for this 3D2Go-Kit.
But there the document is extremly confusing about the LEDs: [Link](https://www.infineon.com/dgdl/Board_Users_Manual_XMC_2Go_Kit_with_XMC1100_R1.0.pdf?fileId=db3a3043444ee5dc014453d6c75078c6)
If you have a look in chapter 2, figure 2 the naming of P1.1 as LED2 is absolutely fine.
But one page further, chapter 2.3, table 2, they are saying that P1.0 is LED2 and P1.1 is LED1.

Actually, I would not refer to the official documents, but to the Arduino Wiki: [Link](https://github.com/Infineon/XMC-for-Arduino/wiki/XMC-2Go). Then you just need to know that P1.0 is now connected to the Sensor VDD and that's it.

To control P0.12 (the other LED on the board) you need to add one line in the `pins_arduino.h` of the XMC2Go in your local copy of XMC-for-Arduino.
Like this:

```
const XMC_PORT_PIN_t mapping_port_pin[] =
{
    /* 0  */    {XMC_GPIO_PORT0 , 6},   // SPI-MISO                         P0.6
       ...                  ...               ...                            ...
       ...                  ...               ...                            ...
       ...                  ...               ...                            ...
    /* 17  */   {XMC_GPIO_PORT2 , 2}    // DEBUG_RX                         P2.2 (INPUT ONLY)
    /* 18  */   {XMC_GPIO_PORT0 , 12}   // LED_3                            P0.12 (just for 3D 2Go Kit)
};
```

Here is the link to the online version of that file: [Link](https://github.com/Infineon/XMC-for-Arduino/blob/master/variants/XMC1100/config/XMC1100_XMC2GO/pins_arduino.h)

Then you should be able to control this LED as Arduino pin 18:
   `pinMode(18, OUTPUT);`
   `digitalWrite(18, HIGH);`
