### ISSUE TITLE
TLE493D

### ISSUE THREAD

**Issue by nikkadim** [Infineon/3D-Magnetic-Sensor-2GO#2]
Should this library work with new TLE493D sensor? In MagneticSensor3D.h you have some notes about sensor configuration, but according spec this sensor have at least two Fast Mode's (7.5 kHz and 5.7 kHz).

PS: Tried to communicated with TLE493D via this library, no luck.

**Comment by mhollfelder** [comment]
Currently, the library has been developed for the TLV493D and will only work with this one.
So it is unfortunately not working with the TLE493D right now, sorry!

We are currently working on some other libraries and I will discuss this one as a request.

Best regards,

Manuel

**Comment by nikkadim** [comment]
Thank you @mhoechner! TLV494D works just fine with this lib, thank you for your work! Can't wait to try TLE493E with a higher sampling rate.

**Comment by nikkadim** [comment]
@mhoechner any updates when TLE493 will be available?
Thank you.

**Comment by mhoechner** [comment]
@nikkadim 

Finally the arduino library for the TLE493D-W2B6 is available at: 
[TLE493D-W2B6 Lib ](https://github.com/Infineon/TLE493D-W2B6-3DMagnetic-Sensor)

With this first version you should be able to communicate with your TLE493D.
However to enable all features of this sensor (i.e. fast mode) some further work on this Library is required.

BR
Moritz

**Comment by nikkadim** [comment]
@mhollfelder  terrific! Thank you very much!

**Comment by mhollfelder** [comment]
I will close this issue, if you need more help, please let us know.

Best regards,

Manuel

**Comment by faccolo** [comment]
@mhollfelder 
Hello,
sorry for the question.
I have TLE493D-W2B6-A3
could i use your arduino lib for this device?
best regards,
Francesco
