### ISSUE TITLE
14 15

### ISSUE THREAD

**Issue by ghost** [Infineon/3D-Magnetic-Sensor-2GO#4]
What are pins 14 and 15 
pinMode(14, OUTPUT);  SDL SLK ?
pinMode(15, OUTPUT);  SDL SLK ?

**Comment by mhollfelder** [comment]
Hi comarius,

These are board specific pins which are connected to the on-board LEDs.

If you have a look on the XMC 2Go implementation for Arduino (the 3D Magnetic Sensor 2Go is based on the XMC 2Go), you will see that pin 14 and 15 is connected to the two additional LEDs of the XMC 2Go. 
The pin out diagram is shown in the wiki [here](https://github.com/Infineon/XMC-for-Arduino/wiki/XMC-2Go).

We are currently rewriting the library and cleaning it up to separate it from from any board specific implementation. 
If you have further questions, please let me know.

Best regards,

Manuel

**Comment by mhollfelder** [comment]
We removed these lines from the new examples as they were confusing if the sensor is used on an own board or with other boards from us.

The new release will take care of the changes, in the meantime, we will push the code to the master branch.

Best regards,

Manuel
